### ISSUE TITLE
KeyError: 'incident_longitude'

### ISSUE THREAD

**Issue by palewire** [datadesk/calfire-wildfires#4]
```python
$ pipenv run python
Python 3.6.10 (default, Dec 19 2019, 23:04:32) 
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import calfire_wildfires
>>> data = calfire_wildfires.get_active_fires()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/palewire/Code/calfire-wildfires/calfire_wildfires/__init__.py", line 44, in get_active_fires
    fires = get_fires()['features']
  File "/home/palewire/Code/calfire-wildfires/calfire_wildfires/__init__.py", line 32, in get_fires
    ) for r in tidy_reader]
  File "/home/palewire/Code/calfire-wildfires/calfire_wildfires/__init__.py", line 32, in <listcomp>
    ) for r in tidy_reader]
KeyError: 'incident_longitude'
```

**Comment by palewire** [comment]
Looks like we are 404'ing.

```python
$ calfirewildfires active-fires
[{'<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN""http://www.w3.org/TR/html4/strict.dtd">': '<HTML><HEAD><TITLE>Not Found</TITLE>'}, {'<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN""http://www.w3.org/TR/html4/strict.dtd">': '<META HTTP-EQUIV="Content-Type" Content="text/html; charset=us-ascii"></HEAD>'}, {'<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN""http://www.w3.org/TR/html4/strict.dtd">': '<BODY><h2>Not Found</h2>'}, {'<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN""http://www.w3.org/TR/html4/strict.dtd">': '<hr><p>HTTP Error 404. The requested resource is not found.</p>'}, {'<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN""http://www.w3.org/TR/html4/strict.dtd">': '</BODY></HTML>'}]
```
